// Code generated by hertz generator.

package main

import (
	"learn/biz/config"
	"learn/biz/middleware"
	"learn/biz/model"

	"github.com/cloudwego/hertz/pkg/app/server"
)

func Init() {
	middleware.InitJwt()
	config.InitRedis()
	config.InitEmailClient()
	config.InitKubernetesClient()
	db := config.InitDB()
	db.AutoMigrate(
		&model.User{},
		&model.Role{},
		&model.Application{},
	)
}

func main() {
	Init()
	h := server.Default()
	register(h)

	h.Spin()
}
