// Code generated by hertz generator.

package main

import (
	"learn/biz/config"
	"learn/biz/middleware"

	"github.com/hertz-contrib/logger/accesslog"

	"github.com/cloudwego/hertz/pkg/app/server"
)

func Init() {
	middleware.InitJwt()
	config.InitRedis()
	config.InitEmailClient()
	config.InitKubernetesClient()
	config.InitDB()
}

func main() {
	Init()
	h := server.Default()
	h.Use(accesslog.New())
	register(h)

	h.Spin()
}
